package org.krynicki.euler.Problems51to100;

import org.krynicki.euler.Problems1to50.Problem45_TrianglePentagonHexagon.Generator;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.function.IntUnaryOperator;
import java.util.stream.IntStream;

/**
 * Created by K on 2016-11-09.
 */
public class Problem61_CyclicalFigurateNumbers {
    /*
    Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all
    figurate (polygonal) numbers and are generated by the following formulae:

    Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    Square	 	    P4,n=n2	 	1, 4, 9, 16, 25, ...
    Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
    Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
    Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
    The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

    The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
    Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
    This is the only set of 4-digit numbers with this property.
    Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle,
    square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
    */

    public static void main(String[] args) {
        PriorityQueue<Generator> queue = new PriorityQueue<>();

        final long t1 = System.currentTimeMillis();
        Generator[] generators = {
                new Generator(1, t -> t * (t + 1) >> 1),
                new Generator(1, t -> t * t),
                new Generator(1, t -> t * (3 * t - 1) >> 1),
                new Generator(1, t -> t * (2 * t - 1)),
                new Generator(1, t -> t * (5 * t - 3) >> 1),
                new Generator(1, t -> t * (3 * t - 2))
        };

        Queue<List<List<Integer>>> values = new LinkedList<>();
        for (int i = 0; i < generators.length; i++) {
            List<List<Integer>> toAdd = new ArrayList<>(100);

            while (generators[i].value() < 1000) {
                generators[i].next();
            }

            for (int j = 0; j <= 99; j++) {
                toAdd.add(new ArrayList<>(10));
            }

            int nextValue;
            int startDigits;

            while ((nextValue = (int) generators[i].value()) < 10000) {
                startDigits = nextValue / 100;

                if (nextValue % 100 > 10) {
                    toAdd.get(startDigits).add(nextValue);
                }

                generators[i].next();
            }
            values.add(toAdd);
        }

        resolve(values);

        final long t2 = System.currentTimeMillis();

        System.out.println(t2 - t1);


    }

    private static void resolve(Queue<List<List<Integer>>> values) {
        List<List<Integer>> startingList = values.poll();
        int[] chosenValues = new int[6];
        for (List<Integer> list : startingList) {
            for (int value : list) {
                chosenValues[0] = value;
                if(resolve(values, chosenValues, 1)) {
                    System.out.println(Arrays.toString(chosenValues));
                    System.out.println(IntStream.range(0, chosenValues.length).map(new IntUnaryOperator() {
                        @Override
                        public int applyAsInt(int operand) {
                            return chosenValues[operand];
                        }
                    }).sum());
                    return;
                }
            }

        }
    }

    private static boolean resolve(Queue<List<List<Integer>>> values, int[] chosenValues, int current) {
        if (values.isEmpty()) {
            return chosenValues[0] / 100 == chosenValues[current-1] % 100;
        }

        int endDigits = chosenValues[current-1] % 100;
        List<List<Integer>> currentList;
        int left = values.size();
        while (left > 0) {
            currentList = values.poll();
            for (int value : currentList.get(endDigits)) {
                chosenValues[current] = value;
                if (resolve(values, chosenValues, current + 1)) {
                    return true;
                }
            }
            left--;
            values.add(currentList);
        }

        return false;
    }

    private static boolean startsWith(int digits, int val) {
        return val / 100 == digits;
    }

}
