package org.krynicki.euler;

import org.krynicki.euler.Problem45_TrianglePentagonHexagon.Generator;

import javax.persistence.GeneratedValue;
import javax.persistence.criteria.CriteriaBuilder;
import java.util.ArrayList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.function.LongFunction;

/**
 * Created by K on 2016-11-09.
 */
public class Problem61_CyclicalFigurateNumbers {
    /*
    Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all
    figurate (polygonal) numbers and are generated by the following formulae:

    Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    Square	 	    P4,n=n2	 	1, 4, 9, 16, 25, ...
    Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
    Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
    Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
    The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

    The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
    Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
    This is the only set of 4-digit numbers with this property.
    Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle,
    square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
    */

    public static void main(String[] args) {
        PriorityQueue<Generator> queue = new PriorityQueue<>();

        Generator[] generators = {new Generator(1, t -> t * (t + 1) >> 1),
        new Generator(1, t -> t * t ),
        new Generator(1, t -> t * (3 * t - 1) >> 1),
        new Generator(1, t -> t * (2 * t - 1)),
        new Generator(1, t -> t * (5 * t - 3) >> 1),
        new Generator(1, t -> t * (3 * t - 2))};


        List<Integer>[] values = new List[6];
        for(int i = 0;i<6;i++) {
            values[i] = new ArrayList<>(100);
            while(generators[i].value() < 1000) {
                generators[i].next();
            }
            while(generators[i].value() < 10000) {
                values[i].add((int) generators[i].value());
                generators[i].next();
            }
        }

        resolve(values);

        System.out.println();


    }

    private static void resolve(List<Integer>[] values) {
        for(int value:values[0]) {
            resolve(values, 0, value, value);
        }

    }

    private static boolean resolve(List<Integer>[] values, int num, int carryOverValue, int startValue) {
        if(num == values.length) {
            return startsWith(carryOverValue, startValue);
        }


        int endDigits = carryOverValue%100;
        for(int value:values[num%values.length]) {
            if(startsWith(endDigits, value)) {
                if(resolve(values, num + 1, value, startValue)) {
                    System.out.println("LEVEL "+num);
                    System.out.println(value);
                    return true;
                }
            }
        }

        return false;
    }

    private static boolean startsWith(int digits, int val) {
        return val / 100 == digits;
    }

}
