package org.krynicki.euler;

/**
 * Created by K on 2016-09-28.
 */
public class SumEvenFibonacci {

    /*
    * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    * By starting with 1 and 2, the first 10 terms will be:
    *
    * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    *
    * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    * find the sum of the even-valued terms.
    */

    long sumEvenFibonacci(int max) {
        long result = 2;
        int a = 1;
        int b = 2;
        int currentFib = 3;

        while(currentFib < max) {
            currentFib = a + b;

            if(currentFib%2==0) {
                result+=currentFib;
            }

            a = b;
            b = currentFib;
        }

        return result;

    }


    static public void main(String[] args) {
        SumEvenFibonacci t = new SumEvenFibonacci();

        System.out.println(t.sumEvenFibonacci((int) 4E6));
    }

}
